fix: add plugin-generate
salesforcecli/cli pull request #63
Opened 2021-09-28 17:58 UTC by RodEsp

Adds the `sf generate project` command.

@W-9958398@

2021-09-28 17:59 UTC, mdonnalley approved these changes

2021-09-28 20:03 UTC, peternhale submitted a review, later dismissed

2021-09-28 21:26 UTC, peternhale requested changes

2021-09-28 21:26 UTC, peternhale commented on package.json
> +    "@sf/tmp": "npm:@salesforce/templates@52.2.0",
@RodEsp would `@sf/tpl` be a better alias? I see `tmp` and I think `temporary`

2021-09-29 13:36 UTC, peternhale submitted a review, later dismissed

2021-09-29 14:02 UTC, peternhale submitted a review, later dismissed

2021-09-29 22:24 UTC, merged